
import "./globals.css";
import Header from "@/app/components/Header.jsx";
import Nav from "@/app/components/Nav.jsx";
import Footer from "@/app/components/Footer.jsx";

export const metadata = {
  title: "Grocery Application Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     
    >
      <body className="min-h-full flex flex-col">
        <Header/>
       
        { children }
        
        <Footer />
        </body>
    </html>
  );
}
